on:
  pull_request:
  
name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        device:
          - stm32g431
          - stm32g441
          - stm32g471
          - stm32g473
          - stm32g474
          - stm32g483
          - stm32g484
          - stm32g491
          - stm32g4a1
        features:
          - rt,embedded-can-03,unstable-defmt
          - log-rtt,defmt
          - log-itm
          - log-semihost

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: thumbv7em-none-eabihf
          override: true

      - name: Regular build
        run: cargo check --features ${{ matrix.device }} --features ${{ matrix.features }}
      - name: Build examples
        run: cargo check --examples --features ${{ matrix.device }} --features ${{ matrix.features }}
